"""add audio channels

Revision ID: 21c78d676764
Revises: 452b38f8331a
Create Date: 2026-03-08 16:33:01.756271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c78d676764'
down_revision: Union[str, Sequence[str], None] = '452b38f8331a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('audio_channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_profiles') as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_vp_channel_id', 'audio_channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_profiles') as batch_op:
        batch_op.drop_constraint('fk_vp_channel_id', type_='foreignkey')
        batch_op.drop_column('channel_id')
    op.drop_table('audio_channels')
    # ### end Alembic commands ###
